#pragma once

#include "nri_renderer_settings.h"
#include "nri_resources.h"
#include "nri_smoke_authority.h"
#include "nri_smoke_admission.h"
#include "nri_smoke_analytic_carriers.h"
#include "nri_smoke_contracts.h"
#include "nri_smoke_emitters.h"
#include "nri_smoke_grid.h"
#include "nri_smoke_dormant_grid.h"
#include "nri_smoke_dormant_injection.h"
#include "nri_smoke_grid_lighting.h"
#include "nri_smoke_interest.h"
#include "nri_smoke_pulses.h"
#include "nri_smoke_prompt_fallback.h"
#include "nri_smoke_spatial_interest.h"
#include "nri_smoke_view_work.h"
#include "nri_smoke_work_scheduler.h"
#include "v_video.h"

#include <array>
#include <cstdint>
#include <map>
#include <set>
#include <vector>

class NRIRenderer;
struct NRISmokeRouteDesc;

struct NRISmokeStatusSnapshot
{
	bool enabled = false;
	bool mainViewEligible = false;
	bool routeSupported = false;
	uint32_t simulationEpoch = 1;
	uint32_t preparedFrame = UINT32_MAX;
	uint32_t dispatchedFrame = UINT32_MAX;
	uint32_t inputSlot = UINT32_MAX;
	uint32_t outputSlot = UINT32_MAX;
	uint32_t depthSlot = UINT32_MAX;
	uint32_t routeWidth = 0;
	uint32_t routeHeight = 0;
	uint32_t routePlacement = 0;
	uint32_t exposureDomain = 0;
	const char* resetReason = "initial";
	uint32_t froxelWidth = 0;
	uint32_t froxelHeight = 0;
	uint32_t froxelDepth = 0;
	uint32_t particleCapacity = 0;
	uint32_t commandsUploaded = 0;
	uint64_t commandsUploadedTotal = 0;
	uint32_t styleCount = 0;
	uint32_t commandsDropped = 0;
	NRISmokeAdmissionSnapshot admission = {};
	NRISmokeAnalyticCarrierSnapshot analytic = {};
	NRISmokeSpatialInterestSnapshot spatialResidency = {};
	NRISmokeDormantGridStatusSnapshot dormantGrid = {};
	struct AnalyticLightTelemetry
	{
		bool valid = false;
		uint64_t sourceFrame = UINT64_MAX;
		uint32_t epoch = 0u;
		uint32_t profile = 0u;
		uint32_t profileRevision = 0u;
		uint32_t implementation = 2u;
		uint32_t buildDispatchGroups = 0u;
		uint32_t applyDispatchGroups = 0u;
		NRISmokeAnalyticCarrierSnapshot cpu = {};
		uint32_t buildEvents = 0u;
		uint32_t anchorsBuilt = 0u;
		uint32_t anchorsValid = 0u;
		uint32_t anchorsInvalid = 0u;
		uint32_t samplesRequested = 0u;
		uint32_t samplesExecuted = 0u;
		uint32_t evaluations = 0u;
		uint32_t buildVisibilityRays = 0u;
		uint32_t gridSeedHits = 0u;
		uint32_t gridSeedMisses = 0u;
		uint32_t applyFroxelsTested = 0u;
		uint32_t applyFroxelsApplied = 0u;
		uint32_t carrierContributions = 0u;
		uint32_t anchorBlendTaps = 0u;
		uint32_t groupCacheHits = 0u;
		uint32_t missingGroupRecords = 0u;
		uint32_t identityRejects = 0u;
		uint32_t applyVisibilityRays = 0u;
	} analyticLight = {};
	bool analyticEmissiveCarrierOwned = false;
	uint32_t admissionFrame = UINT32_MAX;
	uint64_t admissionRendererFrame = UINT64_MAX;
	uint32_t simulationSubsteps = 0;
	uint32_t representationRequested = 0;
	uint32_t representationEffective = 0;
	bool gridReady = false;
	const char* representationFallback = "none";
	const char* authority = "disabled";
	const char* authorityReason = "initial";
	const char* authorityPreparation = "none";
	bool authorityOperational = false;
	uint32_t authorityTransitionSerial = 0;
	uint32_t authorityTransitionFrame = UINT32_MAX;
	uint64_t particlePayloadBytes = 0;
	uint64_t descriptorSentinelBytes = 0;
	uint32_t particleSimulationDispatches = 0;
	uint32_t gridSimulationDispatches = 0;
	uint32_t particleOpticalDispatches = 0;
	uint32_t gridOpticalDispatches = 0;
	uint32_t particleCommandsRouted = 0;
	uint32_t gridCommandsRouted = 0;
	uint32_t requestedLightMode = 0;
	uint32_t effectiveLightMode = 0;
	bool filteredVisibilityRequested = false;
	bool filteredVisibilityEffective = false;
	bool forceOpaqueVisibility = false;
	bool shadowTlasReady = false;
	uint64_t residentBytes = 0;
	uint64_t indirectCacheBytes = 0;
	uint64_t emissiveReservoirBytes = 0;
	uint64_t directHistoryBytes = 0;
	uint32_t directReuseModeRequested = 0;
	uint32_t directReuseModeEffective = 0;
	uint32_t directReferenceMode = 0;
	bool directHistoryValid = false;
	const char* directHistoryResetReason = "initial";
	uint32_t emissiveReuseModeRequested = 0;
	uint32_t emissiveReuseModeEffective = 0;
	uint32_t emissiveLaneCount = 0;
	bool emissiveReference = false;
	bool emissiveHistoryValid = false;
	bool volumeHistoryRequested = false;
	bool volumeHistoryEffective = false;
	bool volumeHistoryValid = false;
	uint32_t volumeResolvedSlot = UINT32_MAX;
	uint32_t volumeMetaSlot = UINT32_MAX;
	uint32_t volumeHistoryAge = 0;
	uint64_t volumeHistoryBytes = 0;
	const char* volumeHistoryResetReason = "initial";
	uint32_t dlrrModeRequested = 0;
	uint32_t dlrrModeEffective = 0;
	uint32_t indirectCacheModeRequested = 0;
	uint32_t indirectCacheModeEffective = 0;
	uint64_t controlReadbackBytes = 0;
	bool gpuStatsValid = false;
	uint64_t gpuStatsFrame = UINT64_MAX;
	uint32_t gpuStatsEpoch = 0;
	uint32_t activeParticles = 0;
	uint32_t spawnedParticles = 0;
	uint32_t expiredParticles = 0;
	uint32_t liveEvictions = 0;
	uint32_t columnOverflow = 0;
	uint32_t wideParticlesProjected = 0;
	uint32_t wideGlobalDrops = 0;
	uint32_t fineColumnReferences = 0;
	uint32_t wideCellReferences = 0;
	uint32_t globalDepthReferences = 0;
	uint32_t referenceInvalidLinks = 0;
	uint32_t referenceTraversalLimitExits = 0;
	uint32_t fineTierParticles = 0;
	uint32_t wideTierParticles = 0;
	uint32_t globalTierParticles = 0;
	uint32_t fineOccupiedCells = 0;
	uint32_t wideOccupiedCells = 0;
	uint32_t globalOccupiedSlices = 0;
	uint32_t fineMaximumCellReferences = 0;
	uint32_t wideMaximumCellReferences = 0;
	uint32_t globalMaximumCellReferences = 0;
	uint32_t maximumDepthSpan = 0;
	uint32_t maximumCandidatesPerFroxel = 0;
	uint32_t occupiedCount = 0;
	uint32_t occupiedOverflow = 0;
	uint32_t mediumCandidateTests = 0;
	uint32_t pointFroxelsProcessed = 0;
	uint32_t directionalFroxelsProcessed = 0;
	uint32_t directionalSamples = 0;
	uint32_t directionalShadowRays = 0;
	uint32_t directionalShadowVisible = 0;
	uint32_t directionalShadowOccluded = 0;
	uint32_t directionalRadianceClamps = 0;
	uint32_t emissiveFroxelsProcessed = 0;
	uint32_t emissiveSamples = 0;
	uint32_t emissiveCandidateMisses = 0;
	uint32_t emissiveDistanceRejected = 0;
	uint32_t emissiveFacingRejected = 0;
	uint32_t emissiveShadowRays = 0;
	uint32_t emissiveShadowVisible = 0;
	uint32_t emissiveShadowOccluded = 0;
	uint32_t emissiveContributed = 0;
	uint32_t emissiveRadianceClamps = 0;
	uint32_t emissiveReservoirInitial = 0;
	uint32_t emissiveReservoirInvalid = 0;
	uint32_t emissiveTemporalAccepted = 0;
	uint32_t emissiveTemporalRejected = 0;
	uint32_t emissiveSpatialAccepted = 0;
	uint32_t emissiveSpatialRejected = 0;
	uint32_t emissiveFinalEvaluations = 0;
	uint32_t emissiveSourceClamps = 0;
	uint32_t emissiveRemovedEnergy = 0;
	uint32_t emissiveMaximumAge = 0;
	uint32_t emissiveReferenceSamples = 0;
	uint32_t emissiveReferenceRays = 0;
	uint32_t emissiveIdentityRejects = 0;
	uint32_t emissiveInnerRisSets = 0;
	uint32_t emissiveInnerPointProposals = 0;
	uint32_t emissiveInnerZeroProposals = 0;
	uint32_t emissiveInnerRisRejects = 0;
	uint32_t emissiveInnerSelections = 0;
	uint32_t emissiveInnerVisibilityRays = 0;
	uint32_t emissiveInnerSourceVisibilityRays = 0;
	uint32_t emissiveInnerVisibilityVisible = 0;
	uint32_t emissiveInnerBlockerReceiverImmediate = 0;
	uint32_t emissiveInnerBlockerReceiverCell = 0;
	uint32_t emissiveInnerBlockerEmitterCell = 0;
	uint32_t emissiveInnerBlockerInterior = 0;
	uint32_t emissiveInnerSourceSelections = 0;
	uint32_t emissiveInnerSourceOverflow = 0;
	uint32_t emissiveTargetVisibilityRays = 0;
	uint32_t emissiveTargetVisibilityVisible = 0;
	uint32_t emissiveTargetBlockerExact = 0;
	uint32_t emissiveTargetBlockerRange = 0;
	uint32_t emissiveTargetBlockerOther = 0;
	uint32_t emissiveTargetWitnessClaim = 0;
	uint32_t emissiveTargetWitnessCandidate = 0xffffffffu;
	uint32_t emissiveTargetWitnessRelation = 0;
	uint32_t emissiveTargetWitnessSamplePrimitive = 0xffffffffu;
	uint32_t emissiveTargetWitnessSampleMaterial = 0xffffffffu;
	uint32_t emissiveTargetWitnessBlockerDataSource = 0xffffffffu;
	uint32_t emissiveTargetWitnessBlockerInstance = 0xffffffffu;
	uint32_t emissiveTargetWitnessBlockerPrimitive = 0xffffffffu;
	uint32_t emissiveTargetWitnessBlockerMaterial = 0xffffffffu;
	uint32_t emissiveTargetWitnessDistanceBits = 0;
	uint32_t indirectFroxelsProcessed = 0;
	uint32_t indirectLocalityRays = 0;
	uint32_t indirectLocalityAgreement = 0;
	uint32_t indirectLocalityOneSided = 0;
	uint32_t indirectLocalityMismatch = 0;
	uint32_t indirectLocalityInvalid = 0;
	uint32_t indirectReferenceRays = 0;
	uint32_t indirectReferenceHits = 0;
	uint32_t indirectReferenceMisses = 0;
	uint32_t indirectSectorContributions = 0;
	uint32_t indirectSkyContributions = 0;
	uint32_t indirectEmissionContributions = 0;
	uint32_t indirectRadianceClamps = 0;
	uint32_t indirectNanRejects = 0;
	uint32_t indirectTemporalAccepted = 0;
	uint32_t indirectTemporalRejected = 0;
	uint32_t indirectSpatialAccepted = 0;
	uint32_t indirectSpatialRejected = 0;
	uint32_t indirectCacheMaximumAge = 0;
	uint32_t indirectCacheClamps = 0;
	uint32_t indirectCacheResolved = 0;
	uint32_t directReceiverSamples = 0;
	uint32_t directFractionalVisibility = 0;
	uint32_t directVisibilityZero = 0;
	uint32_t directVisibilityOne = 0;
	uint32_t directTemporalAccepted = 0;
	uint32_t directTemporalRejected = 0;
	uint32_t directSpatialAccepted = 0;
	uint32_t directSpatialRejected = 0;
	uint32_t directHistoryMaximumAge = 0;
	uint32_t directHistoryResolved = 0;
	uint32_t directHistoryClamps = 0;
	uint32_t directNanRejects = 0;
	uint32_t lightCandidatesTested = 0;
	uint32_t lightDistanceRejected = 0;
	uint32_t lightShadowRays = 0;
	uint32_t lightShadowVisible = 0;
	uint32_t lightShadowOccluded = 0;
	uint32_t lightSoftSamples = 0;
	uint32_t lightRadianceClamps = 0;
	uint32_t filterCandidateHits = 0;
	uint32_t filterAlphaRejects = 0;
	uint32_t filterNoShadowRejects = 0;
	uint32_t filterOneWayRejects = 0;
	uint32_t filterReflectionRejects = 0;
	uint32_t filterPortalContinuations = 0;
	uint32_t filterAcceptedBlockers = 0;
	uint32_t filterMisses = 0;
	uint32_t filterSkipLimitExits = 0;
	uint32_t filterContinuationLimitExits = 0;
	uint32_t filterResourceDowngrades = 0;
};

class NRISmokeSystem
{
public:
	bool Initialize(NRIRenderer& renderer);
	bool PrepareFrame(NRIRenderer& renderer, bool mainViewEligible, const TArray<PathTracingWeaponLightEvent>& weaponEvents);
	bool DispatchRoute(NRIRenderer& renderer, const NRISmokeRouteDesc& route);
	void Reset(const char* reason);
	void Shutdown(NRIRenderer& renderer);
	void PrintStatus(const NRIRenderer& renderer) const;
	void QueueSyntheticInjection();
	const NRISmokeStatusSnapshot& GetStatusSnapshot() const { return mStatus; }

private:
	struct CommandSlot
	{
		NRIBufferResource upload;
		NRIBufferResource device;
		NRIBufferResource analyticUpload;
		NRIBufferResource analyticDevice;
		NRIBufferResource styleUpload;
		NRIBufferResource controlReadback;
		nri::DescriptorSet* inputSet = nullptr;
		nri::DescriptorSet* bufferSet = nullptr;
		nri::DescriptorSet* textureSet = nullptr;
		nri::DescriptorSet* outputSet = nullptr;
		nri::DescriptorSet* lightSet = nullptr;
		nri::DescriptorSet* filteredSceneSet = nullptr;
		bool readbackPending = false;
		bool initialized = false;
		bool readbackInitialized = false;
		uint64_t readbackFrame = UINT64_MAX;
		uint32_t readbackEpoch = 0;
		uint32_t analyticProfile = 0u;
		uint32_t analyticProfileRevision = 0u;
		uint32_t analyticBuildDispatchGroups = 0u;
		uint32_t analyticApplyDispatchGroups = 0u;
		NRISmokeAnalyticCarrierSnapshot analyticSnapshot = {};
	};

	bool EnsureResources(NRIRenderer& renderer, uint32_t representation);
	bool RebuildAuthorityResourcesTransactional(NRIRenderer& renderer, uint32_t representation);
	void UpdateResourceStatus();
	void PublishAuthorityStatus(const char* preparation = "none", const char* fallbackOverride = nullptr);
	bool CreateBuffer(NRIRenderer& renderer, NRIBufferResource& out, uint64_t size, uint32_t stride, nri::BufferUsageBits usage, nri::MemoryLocation location, bool srv, bool uav);
	bool CreateCompatibilityDescriptors(NRIRenderer& renderer);
	bool CreateCompatibilityDescriptors(NRIRenderer& renderer, NRIBufferResource& storage,
		nri::Descriptor*& particleView, nri::Descriptor*& cellView);
	void DestroyCompatibilityDescriptors(NRIRenderer& renderer);
	void DestroyCompatibilityDescriptors(NRIRenderer& renderer, NRIBufferResource& storage,
		nri::Descriptor*& particleView, nri::Descriptor*& cellView);
	bool UploadBytes(NRIRenderer& renderer, NRIBufferResource& upload, const void* data, uint64_t size);
	bool RecordSimulation(NRIRenderer& renderer);
	bool RecordVolume(NRIRenderer& renderer, const NRISmokeRouteDesc& route);
	void DestroyViewResources(NRIRenderer& renderer);
	void DestroyResources(NRIRenderer& renderer);
	void AppendSyntheticCommand(NRIRenderer& renderer);
	NRISmokeGridServices BuildGridServices(NRIRenderer& renderer) const;
	static bool LoadGridShaderBlob(void* user, const char* fileName, std::vector<uint8_t>& outBlob);
	static void WaitForGridCommands(void* user, const char* reason);

	NRISmokeSettings mSettings = {};
	NRISmokeStatusSnapshot mStatus = {};
	nri::PipelineLayout* mPipelineLayout = nullptr;
	std::array<nri::Pipeline*, (size_t)NRISmokePass::Count> mPipelines = {};
	std::vector<CommandSlot> mCommandSlots;
	NRIBufferResource mStyleBuffer;
	NRIBufferResource mCompatibilityStorage;
	nri::Descriptor* mCompatibilityParticleView = nullptr;
	nri::Descriptor* mCompatibilityCellView = nullptr;
	NRIBufferResource mParticles;
	NRIBufferResource mControl;
	NRIBufferResource mFineCells;
	NRIBufferResource mWideCells;
	NRIBufferResource mGlobalDepthCells;
	NRIBufferResource mReferenceNext;
	NRIBufferResource mParticleDirectionalVisibility;
	NRIBufferResource mFroxelMedium;
	NRIBufferResource mFroxelIntegrated;
	NRIBufferResource mFroxelPhase;
	NRIBufferResource mFroxelSource;
	NRIBufferResource mOccupiedFroxelIndices;
	NRIBufferResource mIndirectHistory;
	NRIBufferResource mIndirectScratch;
	NRIBufferResource mEmissiveCurrent;
	NRIBufferResource mEmissiveTemporal;
	NRIBufferResource mEmissiveHistory;
	NRIBufferResource mDirectCurrent;
	NRIBufferResource mDirectHistory;
	NRIBufferResource mAnalyticTileHeaders;
	NRIBufferResource mAnalyticTileIndices;
	NRIBufferResource mAnalyticFroxelMedium;
	NRIBufferResource mAnalyticEmissiveA;
	NRIBufferResource mAnalyticEmissiveB;
	NRISmokeEmitterSystem mEmitters;
	NRISmokeAuthority mAuthority;
	NRISmokeGrid mGrid;
	NRISmokeDormantGrid mDormantGrid;
	NRISmokeGridLighting mGridLighting;
	NRISmokeInterestTracker mInterest;
	NRISmokeSpatialInterestOwner mSpatialInterest;
	NRISmokeViewWork mViewWork;
	NRISmokePulseOwner mPulseOwner;
	NRISmokePromptFallback mPromptFallback;
	NRISmokeAnalyticCarriers mAnalyticCarriers;
	NRISmokeAnalyticTrailBridge mAnalyticTrailBridge;
	NRISmokeWorkScheduler mWorkScheduler;
	std::vector<NRISmokeStyleGpu> mStyles;
	std::vector<NRISmokeInjectionCommandGpu> mPendingCommands;
	std::vector<NRISmokePulseEnqueueInfo> mPendingPulseEnqueueInfo;
	std::vector<NRISmokeAnalyticTrailObservationBatch> mPendingTrailObservations;
	std::vector<NRISmokeInjectionCommandGpu> mSelectedGridCommands;
	std::vector<NRISmokeAnalyticCarrierRequest> mPendingAnalyticRequests;
	std::vector<NRISmokeDormantGridWorkGpu> mDormantDemotions;
	std::vector<NRISmokeDormantGridWorkGpu> mDormantPromotions;
	NRISmokeDormantInjectionBuildResult mDormantInjectionBuild;
	std::map<NRISmokeSpatialCoordinate, NRISmokeSpatialBrickObservation> mDormantAuthorities;
	std::set<NRISmokeSpatialCoordinate> mDormantPendingDemotions;
	NRISmokeAdmissionScheduler mAdmissionScheduler;
	uint64_t mPulsePlanToken = 0;
	uint32_t mResourceParticleCapacity = 0;
	uint32_t mResourceFroxelWidth = 0;
	uint32_t mResourceFroxelHeight = 0;
	uint32_t mResourceFroxelDepth = 0;
	uint32_t mResourceStyleCapacity = 0;
	uint32_t mLastPreparedFrame = UINT32_MAX;
	uint32_t mLastSimulatedFrame = UINT32_MAX;
	uint32_t mLastGridBrickCapacity = 0;
	uint64_t mLastDormantResultFrame = UINT64_MAX;
	float mLastGridCellSize = 0.0f;
	bool mGridLayoutTracked = false;
	uint32_t mNextCommandSerial = 1;
	float mAccumulator = 0.0f;
	double mLastGameplaySeconds = -1.0;
	double mParticleSimulationSeconds = 0.0;
	double mPromptSimulationSeconds = 0.0;
	double mLatestParticleDeathSeconds = 0.0;
	bool mMayHaveParticleSmoke = false;
	bool mSyntheticRequested = false;
	bool mNeedsClear = true;
	bool mControlCopyPending = false;
	bool mResourcesInitialized = false;
	bool mParticleResourcesInitialized = false;
	bool mViewResourcesInitialized = false;
	bool mResourceLegacyEmissiveFull = true;
	bool mResourceParticlePayload = false;
	bool mIndirectHistoryValid = false;
	bool mEmissiveHistoryValid = false;
	uint32_t mLastEmissiveReuseMode = 0;
	uint32_t mLastEmissiveGeneration = 0;
	uint32_t mLastEmissiveFrame = UINT32_MAX;
	uint32_t mLastEmissiveRepresentation = UINT32_MAX;
	uint32_t mLastEmissiveLaneCount = 0;
	uint32_t mLastEmissiveLightMode = 0;
	uint32_t mLastEmissiveVisibilityBackend = 0;
	bool mDirectHistoryValid = false;
	uint32_t mLastDirectFrame = UINT32_MAX;
	uint32_t mLastDirectReuseMode = 0;
	uint32_t mLastDirectReferenceMode = 0;
	uint32_t mLastDirectQuality = 0;
	uint32_t mLastDirectLightMode = 0;
	uint32_t mLastDirectLightSamples = 0;
	uint32_t mLastDirectSimulationEpoch = 0;
	uint32_t mLastDirectVisibilityBackend = 0;
	uint64_t mLastDirectDirectionalHash = 0;
	bool mVolumeHistoryValid = false;
	uint32_t mLastVolumeFrame = UINT32_MAX;
	uint32_t mLastVolumeWidth = 0;
	uint32_t mLastVolumeHeight = 0;
	uint32_t mLastVolumePlacement = UINT32_MAX;
	uint32_t mLastVolumeSimulationEpoch = 0;
	bool mLastVolumeHistoryEnabled = false;
	uint64_t mLastVolumeLightingHash = 0;
	uint64_t mLastSmokeVisualHash = 0;
	uint32_t mLastIndirectCacheMode = 0;
	uint64_t mLastIndirectSectorHash = 0;
	uint64_t mLastIndirectSkyKey = 0;
	uint64_t mLastIndirectEmissiveHash = 0;
};
